kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: yrfs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: yrfs-provisioner
    spec:
      serviceAccountName: yrfs-provisioner
      containers:
        - name: yrfs-provisioner
          image: yrfs-provisioner:latest
          imagePullPolicy: "IfNotPresent"
