#!/bin/bash

usage() {
	err "Invalid usage. Usage: "
	err "\t$0 init"
	err "\t$0 mount <mount dir> <json params>"
	err "\t$0 unmount <mount dir>"
	exit 1
}

err() {
	echo -ne $* 1>&2
}

log() {
	echo -ne $* >&1
}

isyrfs() {
	YRFS='/mnt/yrfs/'
	TYPE=`findmnt -n ${YRFS} 2>/dev/null | cut -d' ' -f3`
	if [ "$TYPE" == "yrfs" ]; then
		echo "0"
	else
		echo "1"
	fi
}

ismounted() {
	MOUNT=`findmnt -n ${MNTPATH} 2>/dev/null | cut -d' ' -f1`
	if [ "${MOUNT}" == "${MNTPATH}" ]; then
		echo "1"
	else
		echo "0"
	fi
}

domount() {
	YRFS='/mnt/yrfs/kubernetes/'
	MNTPATH=$1

	KPATH=$(echo $2 | jq -r '.path')

	YRFS_PATH=${YRFS}${KPATH}


	option=$(echo $2 | jq -r '.accessMode')

	mode='rw'
	case $option in
		ReadOnlyMany)
			mode='ro'
			;;
		ReadWriteOnce)
			mode='rw'
			;;
		ReadWriteMany)
			mode='rw'
			;;
		*)
			mode='rw'
			;;
	esac

	if [ $(isyrfs) -eq 1 ] ; then
		err "{\"status\": \"Failure\", \"message\": \"Failed to mount, ${YRFS_PATH} is not yrfs\"}"
		exit 1
	fi

	if [ $(ismounted) -eq 1 ] ; then
		log '{"status": "Success"}'
		exit 0
	fi

	mkdir -p ${YRFS_PATH} &> /dev/null
	mkdir -p ${MNTPATH} &> /dev/null

	mount --bind -o $mode ${YRFS_PATH} ${MNTPATH} &> /dev/null
	if [ $? -ne 0 ]; then
		err "{ \"status\": \"Failure\", \"message\": \"Failed to mount ${YRFS_PATH} at ${MNTPATH}\"}"
		exit 1
	fi
	log '{"status": "Success"}'
	exit 0
}

unmount() {
	MNTPATH=$1
	if [ $(ismounted) -eq 0 ] ; then
		log '{"status": "Success"}'
		exit 0
	fi

	umount ${MNTPATH} &> /dev/null
	if [ $? -ne 0 ]; then
		err "{ \"status\": \"Failed\", \"message\": \"Failed to unmount volume at ${MNTPATH}\"}"
		exit 1
	fi

	log '{"status": "Success"}'
	exit 0
}

op=$1

if ! command -v jq >/dev/null 2>&1; then
	err "{ \"status\": \"Failure\", \"message\": \"'jq' binary not found. Please install jq package before using this driver\"}"
	exit 1
fi

if [ "$op" = "init" ]; then
	log '{"status": "Success", "capabilities": {"attach": false}}'
	exit 0
fi

if [ $# -lt 2 ]; then
	usage
fi

shift

case "$op" in
	mount)
		domount $*
		;;
	unmount)
		unmount $*
		;;
	*)
		log '{"status": "Not supported"}'
		exit 0
esac

exit 1
