apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: "yr/yrfs"
    fsType: "yrfs"
    options:
      path: "k8s-yrfs-pv-1"
      accessMode: "ReadWriteMany"
